### PR TITLE
dubugged the userPofile.jsx page and tested its functionality

### PR DESCRIPTION
**Pull request by Isaac-Amano**
dubugged the userPofile.jsx page and tested its functionality

### CODE REVIEW

**Review by JeaneeAllen — APPROVED** [review]
Reviewed. Some conflicts. Review.

**Review by JeaneeAllen — CHANGES_REQUESTED** [review]
Some conflicts. Review.

**Review by Isaac-Amano — COMMENTED** [review]
Restructured the whole userProfile.jsx page and edited the serverside, added MUI to style it

**Review by tracymsmith — APPROVED** [review]
Looks good!

**Review by aharasymiw — CHANGES_REQUESTED** [review]
Isaac, fix your conflicts!!!!
(This is for demo reasons, Isaac is awesome!)

**Review by aharasymiw — APPROVED** [review]

**Review by JeaneeAllen — APPROVED** [review]

**Pull request merged**
